### ISSUE TITLE
Allow defining and creating virtual OpenFOAM environments?

### ISSUE THREAD

**Issue by petebachant** [gerlero/styro#35]
For example, a specific version of OpenFOAM and a set of extension packages with their own versions, like a Conda or virtual environment in Python. This might be overkill since extensions will typically not interact/conflict with each other but seems like a logical next step.

Environments could be defined in YAML like:

```yaml
name: of-2406-aco
openfoam: v2406
packages:
  - libAcoustics>=1.0
```

Questions:

1. Should these be stored system-wide with names or should they simply live in a simulation project folder? Conda does the former and venv does the latter.
